server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:6060/e-commerce
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: java
    password: root

rabbitmq:
  exchange-auth: auth-exchange
  registerMailQueue: mail-queue
  registerMailBindingKey: mail-key