server:
  port: 9093
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: e-commerce
      username: Java
      password: root
      auto-index-creation: true

logging:
  file:
    name: sale-service/src/main/resources/logs/sale-app.log  #D:\Btk-Ecommerce\product-service\logs\sale-app.log  #loglamanın yapılacağı path yolu
  level:
    com.btk.service: DEBUG #loglama seviyesi